### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by flavio**
This is a follow up from https://github.com/spinkube/runtime-class-manager/pull/46, it addresses the comments left inside of the review.

Please forgive me for having created a unique PR, if you want I can split each commit into separate PRs.

These are the changes done:

- chore(deps): update golangci-lint
- refactor: replace occurrences of KWasm
- fix: attempt to install shim on all nodes
- refactor: remove unneeded code
- refactor: define rollout strategy type and use constants
- fix: not all rollout strategies are implemented yet

### CODE REVIEW

**Review by voigt — APPROVED** [review]
Hey @flavio ,
this looks like a very nice PR. Thank you!

I think, that we still have a "bit" of kwasm in the project (at least in `config/crd/bases/runtime.kwasm.sh_shims.yaml)`). Shall we remove that in a separate PR?

**Comment by flavio** [comment]
@voigt do you mind if I do this change with another PR? Right now I'm having troubles testing the changes since tilt is broken (that's the next thing I want to address). I would feel more confident about this needed change if I were able to test it

**Comment by voigt** [comment]
@flavio fine for me. Let me know if you need any help with the tilt file/config!

**Comment by flavio** [comment]
> @flavio fine for me. Let me know if you need any help with the tilt file/config!

Sure, I'll probably send something late next week. I've a short vacation coming up and I've some work stuff that has higher priority

**Pull request merged**
